# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conta',
            name='data',
            field=models.DateField(default=datetime.date(2017, 6, 29)),
        ),
    ]
