# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0003_auto_20170702_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
