# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0004_auto_20170702_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemconta',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo_produto',
        ),
        migrations.AddField(
            model_name='itemconta',
            name='tipo_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_produtos', to='consumo.TipoProduto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='consumo.Produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conta',
            name='data',
            field=models.DateField(default=datetime.date(2017, 7, 3)),
        ),
    ]
