# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0005_auto_20170703_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproduto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='consumo.Categoria'),
            preserve_default=False,
        ),
    ]
