# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0007_auto_20170703_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumo.Mesa'),
        ),
    ]
