# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0008_auto_20170703_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data',
            field=models.DateField(default=datetime.date(2017, 7, 6)),
        ),
    ]
