# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0009_auto_20170706_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data',
            field=models.DateField(default=datetime.date(2017, 7, 10)),
        ),
    ]
