# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0012_auto_20170719_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconta',
            name='parcial',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conta',
            name='data',
            field=models.DateField(default=datetime.date(2017, 7, 21)),
        ),
        migrations.AlterField(
            model_name='itemconta',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
