# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0013_auto_20170721_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconta',
            name='parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
