# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0015_auto_20170722_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconta',
            name='parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
