# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0017_auto_20170722_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproduto',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
