# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0020_auto_20170726_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconta',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
