# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0023_auto_20170814_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data',
            field=models.DateField(default=datetime.date(2017, 8, 15)),
        ),
    ]
